// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Note struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
	VisibleAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Session struct {
	ID             string
	UserID         sql.NullString
	CsrfToken      string
	IpAddress      sql.NullString
	UserAgent      sql.NullString
	ExpiredAt      time.Time
	LastActivityAt sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
