// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf_token, ip_address, user_agent, expired_at, last_activity_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, csrf_token, ip_address, user_agent, expired_at, last_activity_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID             string
	UserID         sql.NullString
	CsrfToken      string
	IpAddress      sql.NullString
	UserAgent      sql.NullString
	ExpiredAt      time.Time
	LastActivityAt sql.NullTime
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiredAt,
		arg.LastActivityAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiredAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, csrf_token, ip_address, user_agent, expired_at, last_activity_at, created_at, updated_at FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiredAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionLastActivity = `-- name: UpdateSessionLastActivity :exec
UPDATE sessions
SET 
  last_activity_at = now()
WHERE id = ?
`

func (q *Queries) UpdateSessionLastActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastActivity, id)
	return err
}
