// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf_token, ip_address, user_agent, expired_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, csrf_token, ip_address, user_agent, expired_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string
	UserID    sql.NullString
	CsrfToken string
	IpAddress sql.NullString
	UserAgent sql.NullString
	ExpiredAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiredAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, csrf_token, ip_address, user_agent, expired_at, created_at, updated_at FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionExpired = `-- name: UpdateSessionExpired :exec
UPDATE sessions
SET 
  expired_at = ?
WHERE id = ?
`

type UpdateSessionExpiredParams struct {
	ExpiredAt time.Time
	ID        string
}

func (q *Queries) UpdateSessionExpired(ctx context.Context, arg UpdateSessionExpiredParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionExpired, arg.ExpiredAt, arg.ID)
	return err
}
